# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 16:05
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='res_color',
            field=colorful.fields.RGBColorField(default='#5DADE2'),
        ),
    ]
